### ISSUE TITLE
Menufiles

### ISSUE THREAD

**Issue by szabto** [uGiFarukh/public_promodlive220#1]
Hey!

In this edition menu files are not "public".
This contains only scriptfiles.
Why did you left them there? (menus)

**Comment by uGiFarukh** [comment]
Menu Files are not provided to me from promod team. The only source I got is here. Menu files are also here but encrypted...

**Comment by szabto** [comment]
I have all of them, if you ever need.

**Comment by uGiFarukh** [comment]
That would be very grateful if you can provide me pml220 menu files...

**Comment by szabto** [comment]
Check my repositories.
Cheers :)
Kubu

**Comment by uGiFarukh** [comment]
You might make a pull request here for the menu files if you want to contribute to this project. I am not going to copy your menu files in my repo. You need to make a pull request...

**Comment by szabto** [comment]
I dont want to contribute, just wanted to help you in full raw.
But if u use the, bug reportings are welcome :)

**Comment by uGiFarukh** [comment]
Thanks :)
